# Generated by Django 5.2.5 on 2025-08-07 08:10

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_holiday', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('reserve_date', models.DateField(default=datetime.date(2025, 7, 1))),
                ('reserve_time', models.TimeField(default=datetime.time(8, 0))),
                ('is_active', models.BooleanField(default=True)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.availableslot')),
            ],
        ),
    ]
