# Generated by Django 5.2.3 on 2025-08-06 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reserve_is_active_reserve_reserve_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableslot',
            name='is_available',
        ),
        migrations.AddField(
            model_name='availableslot',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserve',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.availableslot'),
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='time',
            field=models.TimeField(),
        ),
    ]
